logging:
  level: "DEBUG"
  log_format: '%(asctime)s  %(name)s  %(levelname)s: %(message)s'
  output_file:
    name: "mqtt_remote.log"
    max_size: 5242880
    max_backups: 2
  log_base_client: True

mqtt_broker:
  ip: "192.168.1.123"
  port: 1883
  user_name: 'monty'
  password_required: True
  password: 'monty_python'
  keepalive: 60

mqtt_session:
  protocol: "3.1.1"
  transport: 'tcp'
  clean: True

subscriptions:
  this_mqtt_client:
    name: "spam"
    qos: 0